# Generated by Django 5.0.5 on 2024-05-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_alter_whitelistrow_col_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistrow',
            name='col_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='blacklistrow',
            name='col_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='blacklistrow',
            name='col_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Club'),
        ),
        migrations.AlterField(
            model_name='blacklistrow',
            name='col_4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Union'),
        ),
        migrations.AlterField(
            model_name='blacklistrow',
            name='col_5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='blacklistrow',
            name='col_6',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Over Information'),
        ),
        migrations.AlterField(
            model_name='whitelistrow',
            name='col_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Club'),
        ),
        migrations.AlterField(
            model_name='whitelistrow',
            name='col_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Union'),
        ),
    ]
