# Generated by Django 5.0.5 on 2024-05-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_alter_blacklistrow_col_1_alter_blacklistrow_col_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Contact')),
            ],
        ),
        migrations.RemoveField(
            model_name='blacklistrow',
            name='col_2',
        ),
        migrations.AddField(
            model_name='blacklistrow',
            name='col_2',
            field=models.ManyToManyField(blank=True, to='main_page.contactitem', verbose_name='Contact'),
        ),
    ]
